VGrad-Empty/Models/OtherProject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace VGrad_Empty.Models
{
    public class OtherProject
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OtherProjectId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required]
        public string Organization { get; set; }

        public Student Student { get; set; }

    }
}

VGrad-Empty/Controllers/OtherProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VGrad_Empty.Models;

namespace VGrad_Empty.Controllers
{
    public class OtherProjectsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: OtherProjects
        public ActionResult Index()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int userId = Convert.ToInt32(Session["UserId"]);
            return View(db.OtherProjects.Include("Student").Where(s => s.Student.User.UserId == userId).ToList());
        }

        // GET: OtherProjects/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OtherProject otherProject = db.OtherProjects.Find(id);
            if (otherProject == null)
            {
                return HttpNotFound();
            }
            return View(otherProject);
        }

        // GET: OtherProjects/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        // POST: OtherProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OtherProjectId,Title,Description,Organization")] OtherProject otherProject)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                int userId = Convert.ToInt32(Session["UserId"]);
                var student = db.Students.Where(s => s.User.UserId == userId).FirstOrDefault();
                if (student == null)
                {
                    TempData["msg"] = "No student information found!";
                    return RedirectToAction("Login", "Home");
                }
                student.OtherProjects.Add(otherProject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(otherProject);
        }

        // GET: OtherProjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int userId = Convert.ToInt32(Session["UserId"]);
            OtherProject otherProject = db.OtherProjects.Include("Student").Where(s => s.OtherProjectId == id).FirstOrDefault();

            if (otherProject.Student.User.UserId != userId)
            {
                TempData["msg"] = "Kindly login with connected account";
                RedirectToAction("Login", "Home");
            }
            if (otherProject == null)
            {
                return HttpNotFound();
            }
            return View(otherProject);
        }

        // POST: OtherProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OtherProjectId,Title,Description,Organization")] OtherProject otherProject)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(otherProject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(otherProject);
        }

        // GET: OtherProjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int userId = Convert.ToInt32(Session["UserId"]);
            OtherProject otherProject = db.OtherProjects.Include("Student").Where(s => s.OtherProjectId == id).FirstOrDefault();

            if (otherProject.Student.User.UserId != userId)
            {
                TempData["msg"] = "Kindly login with connected account";
                RedirectToAction("Login", "Home");
            }
            if (otherProject == null)
            {
                return HttpNotFound();
            }
            return View(otherProject);
        }

        // POST: OtherProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int userId = Convert.ToInt32(Session["UserId"]);
            OtherProject otherProject = db.OtherProjects.Include("Student").Where(s => s.OtherProjectId == id).FirstOrDefault();

            if (otherProject.Student.User.UserId != userId)
            {
                TempData["msg"] = "Kindly login with connected account";
                RedirectToAction("Login", "Home");
            }
            db.OtherProjects.Remove(otherProject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VGrad-Empty/Views/OtherProjects/Create.cshtml
@model VGrad_Empty.Models.OtherProject

@{
    ViewBag.Title = "Add Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Project</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <br/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "materialize-textarea" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Organization, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Organization, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Organization, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default right" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VGrad-Empty/Views/OtherProjects/Delete.cshtml
@model VGrad_Empty.Models.OtherProject

@{
    ViewBag.Title = "Delete Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Project?</h3>
<div>
    <hr />
    <br/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default right" />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VGrad-Empty/Views/OtherProjects/Details.cshtml
@model VGrad_Empty.Models.OtherProject

@{
    ViewBag.Title = "Project Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Project Details</h2>

<div>
    <hr />
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OtherProjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VGrad-Empty/Views/OtherProjects/Edit.cshtml
@model VGrad_Empty.Models.OtherProject

@{
    ViewBag.Title = "Edit Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OtherProjectId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "materialize-textarea" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Organization, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Organization, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Organization, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default right" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VGrad-Empty/Views/OtherProjects/Index.cshtml
@model IEnumerable<VGrad_Empty.Models.OtherProject>

@{
    ViewBag.Title = "My Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Projects</h2>
For Authenticity purposes we can't allow students to add <b>Final Year Projects</b>, it could only be added by Compitent authority. Try contacting your Co-ordinator. 
<br/>
Meanwhile you can add your other projects you have done so far.
<p>
    @Html.ActionLink("Add More", "Create", "OtherProjects", htmlAttributes: new { @class = "btn btn-default right" })
</p>
<table class="table hoverable bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Organization)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Organization)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OtherProjectId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OtherProjectId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OtherProjectId })
        </td>
    </tr>
}

</table>